name: superficialintellectual
favicon: null
layout_spectrum: 0.6289071345236152
typography_spectrum: 0.18533941451460123
title: Title?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7315626374911517
  lightness: 0.9357797459233552
  saturation: 0.23814622801728547
  rhythmicContrast: 0.9923528428189456
purpose: []
